exploits:
  - name: NoPac
    vulnerable_os_patterns:
      - "2012"
      - "2016"
      - "2019"
    poc_function: run_nopac_poc
  - name: PrintSpool
    vulnerable_os_patterns:
      - "2019"
    poc_function: run_printspool_poc
